replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/inventaris-barang/inventory-app
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  host: ""
#  tls: false

resources:
  limits: {}
  requests: {}

persistence:
  enabled: true
  storageClass: "ocs-external-storagecluster-ceph-rbd"
  accessMode: ReadWriteOnce
  size: 1Gi

env:
  APP_ENV:
  APP_DEBUG: "false"
  APP_KEY:
  DB_CONNECTION:
  DB_HOST:
  DB_PORT:
  DB_DATABASE:
  DB_USERNAME:
  DB_PASSWORD:
