replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/inventaris-barang/inventory-app
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  host: ""
#  tls: false

route:
  enabled: true
  host: ""

resources:
  limits: {}
  requests: {}

persistence:
  enabled: true
  storageClass: "ocs-external-storagecluster-ceph-rbd"
  accessMode: ReadWriteOnce
  size: 1Gi

env:
  APP_ENV: dev
  APP_DEBUG: "false"
  APP_KEY: ""
  DB_CONNECTION: mysql
  DB_HOST: "mysql.inventaris-barang.svc.cluster.local"
  DB_PORT: "3306"
  DB_DATABASE: "inventory-app_db"
  DB_USERNAME: "inventory-app_user"
  DB_PASSWORD: "pass123"

