apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-app.fullname" . }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.env.APP_KEY | default "" }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | default "changeme" }}
